### ISSUE TITLE
embeddedAssets.test.js e2e test is flaky

### ISSUE THREAD

**Issue by jespertheend** [rendajs/Renda#140]
It keeps timing out at `Verify if changes were saved`
```
Verify if changes were saved ...
    Click asset "New Material.json" ... ok (41ms)
  Verify if changes were saved ... FAILED (30s)
    error: TimeoutError: waiting for function failed: timeout 30000ms exceeded
          const timeoutError = new TimeoutError(
                               ^
        at new WaitTask (https://raw.githubusercontent.com/jespertheend/deno-puppeteer/lib-dom-types/vendor/puppeteer-core/puppeteer/common/IsolatedWorld.js:796:28)
        at IsolatedWorld.waitForFunction (https://raw.githubusercontent.com/jespertheend/deno-puppeteer/lib-dom-types/vendor/puppeteer-core/puppeteer/common/IsolatedWorld.js:662:22)
        at Frame.waitForFunction (https://raw.githubusercontent.com/jespertheend/deno-puppeteer/lib-dom-types/vendor/puppeteer-core/puppeteer/common/Frame.js:530:36)
        at Page.waitForFunction (https://raw.githubusercontent.com/jespertheend/deno-puppeteer/lib-dom-types/vendor/puppeteer-core/puppeteer/common/Page.js:2975:29)
        at getTreeViewItemElementHelper (file:///home/runner/work/Renda/Renda/test/e2e/editor/shared/treeView.js:41:28)
        at getTreeViewItemElement (file:///home/runner/work/Renda/Renda/test/e2e/editor/shared/treeView.js:17:15)
        at fn (file:///home/runner/work/Renda/Renda/test/e2e/editor/src/assets/embeddedAssets.test.js:110:54)
        at async testStepSanitizer (deno:runtime/js/[40](https://github.com/rendajs/Renda/actions/runs/3056488763/jobs/4930705807#step:15:41)_testing.js:4[43](https://github.com/rendajs/Renda/actions/runs/3056488763/jobs/4930705807#step:15:44):7)
        at async TestContext.step (deno:runtime/js/40_testing.js:1328:13)
        at async fn (file:///home/runner/work/Renda/Renda/test/e2e/editor/src/assets/embeddedAssets.test.js:101:3)
```

**Comment by jespertheend** [comment]
We'll close this for now until it pops up again.
