### ISSUE TITLE
Running e2e tests locally on Linux always causes a `TypeError`

### ISSUE THREAD

**Issue by jespertheend** [rendajs/Renda#523]
The tests pass just fine but after the runner is done it shows.
```
error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.165.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.165.0/node/process.ts:314:7
    at innerInvokeEventListeners (ext:deno_web/02_event.js:783:7)
    at invokeEventListeners (ext:deno_web/02_event.js:823:5)
    at dispatch (ext:deno_web/02_event.js:692:9)
    at dispatchEvent (ext:deno_web/02_event.js:1082:12)
    at [ext:{}:{}:{}]cli/worker.rs9038:1:1
```

**Comment by jespertheend** [comment]
See https://github.com/lucacasonato/deno-puppeteer/issues/74

If you run `deno info` and remove the entire `DENO_DIR` folder this should get fixed.
